"""empty message

Revision ID: 05d80e4b003a
Revises: ae95f84e504a
Create Date: 2018-07-11 22:27:03.975348

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '05d80e4b003a'
down_revision = 'ae95f84e504a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reservation', 'end')
    op.drop_column('reservation', 'begin')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reservation', sa.Column('begin', mysql.DATETIME(), nullable=False))
    op.add_column('reservation', sa.Column('end', mysql.DATETIME(), nullable=False))
    # ### end Alembic commands ###
