"""empty message

Revision ID: 16db8838c513
Revises: 72858cae1cec
Create Date: 2018-07-11 19:27:33.486782

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '16db8838c513'
down_revision = '72858cae1cec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('comment_ibfk_2', 'comment', type_='foreignkey')
    op.drop_column('comment', 'to_which')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comment', sa.Column('to_which', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.create_foreign_key('comment_ibfk_2', 'comment', 'reservation', ['to_which'], ['res_id'])
    # ### end Alembic commands ###
