"""empty message

Revision ID: 38de81ac5b6c
Revises: a6df1ebf0352
Create Date: 2018-07-10 10:20:55.203614

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '38de81ac5b6c'
down_revision = 'a6df1ebf0352'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('info', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'info')
    # ### end Alembic commands ###
