"""empty message

Revision ID: 3c286826c8ed
Revises: 973e56832e3d
Create Date: 2018-07-12 11:13:02.744534

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3c286826c8ed'
down_revision = '973e56832e3d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('accommodation', 'acc_price')
    op.drop_column('accommodation', 'acc_capacity')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accommodation', sa.Column('acc_capacity', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('accommodation', sa.Column('acc_price', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100), nullable=True))
    # ### end Alembic commands ###
