"""empty message

Revision ID: 55666f6099cd
Revises: 194dc955c10c
Create Date: 2018-07-11 21:24:10.419914

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '55666f6099cd'
down_revision = '194dc955c10c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reservation', sa.Column('res_price', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reservation', 'res_price')
    # ### end Alembic commands ###
