"""empty message

Revision ID: 6cda2faa2503
Revises: d66b3938e2b2
Create Date: 2018-07-10 11:38:36.923374

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6cda2faa2503'
down_revision = 'd66b3938e2b2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('county',
    sa.Column('county_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('county_name', sa.String(length=20), nullable=False),
    sa.Column('city_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['city_id'], ['city.city_id'], ),
    sa.PrimaryKeyConstraint('county_id'),
    sa.UniqueConstraint('county_id')
    )
    op.create_table('street',
    sa.Column('street_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('street_name', sa.String(length=50), nullable=False),
    sa.Column('county_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['county_id'], ['county.county_id'], ),
    sa.PrimaryKeyConstraint('street_id'),
    sa.UniqueConstraint('street_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('street')
    op.drop_table('county')
    # ### end Alembic commands ###
