"""empty message

Revision ID: 72858cae1cec
Revises: b86b2b5383f0
Create Date: 2018-07-11 14:34:51.650432

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '72858cae1cec'
down_revision = 'b86b2b5383f0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reservation', sa.Column('begin', sa.DateTime(), nullable=False))
    op.add_column('reservation', sa.Column('end', sa.DateTime(), nullable=False))
    op.drop_column('reservation', 'date')
    op.create_unique_constraint(None, 'user', ['email'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.add_column('reservation', sa.Column('date', mysql.DATETIME(), nullable=False))
    op.drop_column('reservation', 'end')
    op.drop_column('reservation', 'begin')
    # ### end Alembic commands ###
