"""empty message

Revision ID: 806570af34ae
Revises: 05d80e4b003a
Create Date: 2018-07-11 22:27:30.193264

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '806570af34ae'
down_revision = '05d80e4b003a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reservation', sa.Column('begin', sa.Integer(), nullable=False))
    op.add_column('reservation', sa.Column('end', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reservation', 'end')
    op.drop_column('reservation', 'begin')
    # ### end Alembic commands ###
