"""empty message

Revision ID: 973e56832e3d
Revises: e55dbcbddfd0
Create Date: 2018-07-11 22:51:50.860013

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '973e56832e3d'
down_revision = 'e55dbcbddfd0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reservation', sa.Column('acc_user_id', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reservation', 'acc_user_id')
    # ### end Alembic commands ###
