"""empty message

Revision ID: cff8cc2629f9
Revises: 3c286826c8ed
Create Date: 2018-07-12 11:13:21.303010

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cff8cc2629f9'
down_revision = '3c286826c8ed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accommodation', sa.Column('acc_capacity', sa.Integer(), nullable=False))
    op.add_column('accommodation', sa.Column('acc_price', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('accommodation', 'acc_price')
    op.drop_column('accommodation', 'acc_capacity')
    # ### end Alembic commands ###
