"""empty message

Revision ID: d66b3938e2b2
Revises: 38de81ac5b6c
Create Date: 2018-07-10 10:57:32.965319

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd66b3938e2b2'
down_revision = '38de81ac5b6c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('datetype',
    sa.Column('type_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('type_name', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('type_id'),
    sa.UniqueConstraint('type_id')
    )
    op.add_column('accommodation', sa.Column('acc_datetype', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'accommodation', 'datetype', ['acc_datetype'], ['type_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'accommodation', type_='foreignkey')
    op.drop_column('accommodation', 'acc_datetype')
    op.drop_table('datetype')
    # ### end Alembic commands ###
