"""empty message

Revision ID: df6bdb273287
Revises: 806570af34ae
Create Date: 2018-07-11 22:30:00.614611

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'df6bdb273287'
down_revision = '806570af34ae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reservation', 'end')
    op.drop_column('reservation', 'begin')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reservation', sa.Column('begin', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.add_column('reservation', sa.Column('end', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
